version: '3.9'

services:
  mongo:
    container_name: mongo_container
    image: 'mongo'
    volumes:
      - mongo-data:/data/db
    networks:
      - queue-net
    env_file: 
      - ./.env.production
    command: mongod --bind_ip_all
    restart: always

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/production/Dockerfile
    ports:
      - '5173:5173'
    restart: always
    env_file: 
      - ./.env.production
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/package.json:/usr/src/app/package.json
    depends_on:
      - server
    networks:
      - queue-net

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/production/Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file: 
      - ./.env.production
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/package.json:/usr/src/app/package.json
      - ./server/nodemon.json:/usr/src/app/nodemon.json
    networks:
      - queue-net

  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: docker/production/Dockerfile
    ports:
      - '8000:8000'
    restart: always
    env_file: 
      - ./.env.production
    volumes:
      - ./admin/src:/usr/src/app/src
      - ./admin/package.json:/usr/src/app/package.json
    depends_on:
      - server
    networks:
      - queue-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/project.manishdashsharma.site/fullchain.pem:/etc/letsencrypt/live/project.manishdashsharma.site/fullchain.pem:ro
      - /etc/letsencrypt/live/project.manishdashsharma.site/privkey.pem:/etc/letsencrypt/live/project.manishdashsharma.site/privkey.pem:ro
    restart: always
    networks:
      - queue-net
    depends_on:
      - server
      - client
      - admin

networks:
  queue-net:
    driver: bridge

volumes:
  mongo-data:
